daemon:
  port: 8080

devices:
  tenma:
    locator: "serial:/dev/tty.usbmodem14141"
    baudrate: 19200
    description: "Tenma-72-2540 programmable DC power supply 30V 5A"

  rigol:
    locator: "tcpip:192.168.88.185:5555"
    description: "Rigol"
